/*
 * Copyright (c) 2017.
 *
 *   This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import {
  AfterViewInit,
  ChangeDetectionStrategy, Component, ElementRef, Inject, OnDestroy, OnInit,
  ViewChild
} from '@angular/core';
import {ActivatedRoute, NavigationStart, Router} from '@angular/router';
import {
  DOCUMENT, isPlatformBrowser, Location, LocationStrategy, PathLocationStrategy
} from '@angular/common';
import {MatSidenav} from '@angular/material';
import {MenuInteractionService} from '../services/menu/menu-interaction.service';
import {Store} from '@ngrx/store';
import * as fromRoot from '../reducers';
import {MediaChange, ObservableMedia} from '@angular/flex-layout';
import {Subscription} from 'rxjs/Subscription';
import {SetTimeoutService} from '../services/timers/timeout.service';
import {SetSelectedService} from '../services/set-selected.service';
import {Observable} from 'rxjs/Observable';
import {AreasFilter} from '../shared/data-types/areas-filter';
import {NavigationServiceB} from '../services/navigation-2/navigation.service';
import {SelectedAreaEvent} from './area-selector/area.component';
import {LoggerService} from '../shared/logger/logger.service';
import {ScrollReadyService} from '../services/observable/scroll-ready.service';

/**
 * This component includes the md-sidenav-container, md-sidenav
 * and the router outlet.
 *
 * The component is responsible for setting the scrollTop value
 * of the scrollable element generated by the md-sidenav-container
 * directive. This assures that list views and item views (which are
 * siblings of the router-outlet inside md-sidenav-container) are
 * positioned correctly on load.
 */
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  providers: [Location, {provide: LocationStrategy, useClass: PathLocationStrategy}],
  changeDetection: ChangeDetectionStrategy.Default
})
export class AppComponent implements AfterViewInit, OnInit, OnDestroy {

  watcher: Subscription;
  areaFilter$: Observable<AreasFilter>;
  selectedAreas: string;
  selectedTypes: string;
  selectedSubject: string;
  selectedGroup: string;
  homeUrl = 'http://libmedia.willamette.edu/academiccommons';
  secondaryUrl = 'http://library.willamette.edu';
  tertiaryUrl = 'http://www.willamette.edu';
  @ViewChild('sidenav') sideNavigate: MatSidenav;
  @ViewChild('appcontent') appContent: ElementRef;

  scrollable: Element;
  state = '';
  /**
   * The y scroll stack tracks the top of the collection view
   * element.  The measurement is obtained from the bounding
   * client rectangle of the #appContent child view and is used
   * to set the scrollTop for the scrollable div (cdk-scrollable)
   * created by the mdSidenavContainer directive (Angular Material).
   * @type {Array}
   */
  yScrollStack: number[] = [];

  constructor(private store: Store<fromRoot.State>,
              private menuService: MenuInteractionService,
              public media: ObservableMedia,
              private router: Router,
              private route: ActivatedRoute,
              @Inject(DOCUMENT) private document,
              private timeoutService: SetTimeoutService,
              private setSelected: SetSelectedService,
              private navigation: NavigationServiceB,
              private logger: LoggerService,
              private scrollReady: ScrollReadyService) {

    this.watcher = new Subscription();
    const mediaWatcher = media.asObservable()
      .subscribe((change: MediaChange) => {
        this.state = change ? `'${change.mqAlias}' = (${change.mediaQuery})` : '';
      });
    this.watcher.add(mediaWatcher);

  }

  goToHome(): void {
    document.location.href = this.homeUrl;
  }

  goToSecondary(): void {
    document.location.href = this.secondaryUrl;
  }

  goToTertiary(): void {
    document.location.href = this.tertiaryUrl;
  }

  areaNavigation(updatedAreaList: SelectedAreaEvent): void {
    this.sideNavigate.close();
    const areaIds = this.navigation.getIds(updatedAreaList.selected);
    this.navigation.navigateFilterRoute(areaIds, this.selectedTypes, this.selectedSubject, this.selectedGroup);
  }

  ngOnInit() {

    const areaList = this.store.select(fromRoot.getAreas);
    const areaFilters = this.store.select(fromRoot.getAreasFilter);
    this.areaFilter$ = Observable.combineLatest(
      areaList,
      areaFilters,
      (areas, selected) => {
        this.selectedAreas = this.navigation.getIds(areas);
        return {
          areas: areas,
          selectedAreas: selected
        }
      }
    );
    const typeQuery: Subscription = this.store.select(fromRoot.getTypesFilter).subscribe(
      types => this.selectedTypes = this.navigation.getIds(types),
      err => console.log(err));
    this.watcher.add(typeQuery);

    const openWatcher = this.menuService.openMenu$.subscribe(open => {
      this.sideNavigate.open().catch((err) => {
        console.log(err);
      });
    });
    this.watcher.add(openWatcher);
  }

  ngAfterViewInit() {

    this.scrollable = this.document.querySelector('.mat-drawer-content');

    // Anticipating angular universal.
    if (isPlatformBrowser) {
      // The scrollReady service knows when ListContainer has received data.
      // We subscribe to it here, and use the position to set the scrollTop value.
      this.scrollReady.subscribe((pos) => {
        this.timeoutService.setTimeout(0, () => {
          if (this.router.url.match(/\/commons\/collection/) ) {
            this.scrollable.scrollTop = pos;
          }
        });
      });

      // This gets the current scroll position when leaving the collection component
      // and sets the value in the scrollReady service. (see above)
      this.router.events.subscribe((event: any) => {
        if (event instanceof NavigationStart) {
          if (!event.url.match(/\/commons\/collection/)) {
            // Get absolute value fo the bounding rectangle for #app-content.
            const top = Math.abs(this.appContent.nativeElement.getBoundingClientRect().top);
            this.logger.info('Bounding rectangle: ' + top);
            this.scrollReady.setPosition(top);
            this.scrollable.scrollTop = 0;
          }
        }
      });
    }
  }

  ngOnDestroy() {
    if (this.watcher) {
      this.watcher.unsubscribe();
    }
    if (this.timeoutService) {
      this.timeoutService.clearTimeout();
    }
    // Unsubscribe all watchers in the service. Each component
    // instance will resubscribe. The prevents the multiple
    // subscriptions within service.
    this.setSelected.unsubscribe();
  }


}
